object Versions {
    const val application = "7.3.0"
    const val androidLibrary = "7.3.0"
    const val android = "1.7.21"
    const val hilt = "2.44"
    const val safeArgs = "2.5.3"
    const val kotlinJvm = "1.7.20"
    const val okHttp = "4.10.0"
    const val retrofit = "2.9.0"
    const val glide = "4.14.2"
    const val viewBinding = "1.5.6"
    const val lifecycles = "2.5.1"
    const val navigation = "2.5.3"
    const val fragment = "1.5.5"
    const val activity = "1.6.1"
    const val coroutines = "1.6.4"
    const val inject = "1"
}